name: GenerateJsonFile

on:
  push: 
    branches:
      - main
  
  pull_request:
    branches:
      - main

  watch:
    types: [started]
   

jobs:
  YML-2-JSON:
    name: Release json
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # star oneself to run

    steps:
    - uses: actions/checkout@v2.1.0
    
    # Set up python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    # install pyYAML
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install pyyaml
    
    # Pyhton script
    - name: Generation
      run: | 
        python generate.py
        echo `date +"%Y-%m-%d %H:%M:%S"` released > build.log

    # Commit json into repo
    - name: Commit
      env:
        $USER_EMAIL: ${{ secrets.USER_EMAIL }}
        $USER_NAME: ${{ secrets.USER_NAME }}
      run: |
        git config --global user.email ${{ secrets.USER_EMAIL }}
        git config --global user.name ${{ secrets.USER_NAME }}
        git add .
        git commit -m "links(json): update YML and generate JSON successfully" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
